# Generated by Django 4.2.7 on 2026-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='number_of_units',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in sq. meters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
