# Generated by Django 4.2.7 on 2026-02-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_number_of_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_number', models.CharField(max_length=50, unique=True)),
                ('termination_type', models.CharField(choices=[('normal', 'Normal Termination'), ('early', 'Early Termination')], max_length=20)),
                ('termination_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('original_security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refundable_amount', models.DecimalField(decimal_places=2, help_text='Amount to be refunded to tenant', max_digits=10)),
                ('unearned_rent', models.DecimalField(decimal_places=2, default=0, help_text='For early termination: unearned rent to be reversed', max_digits=10)),
                ('early_termination_penalty', models.DecimalField(decimal_places=2, default=0, help_text='Penalty charged for early termination', max_digits=10)),
                ('maintenance_charges', models.DecimalField(decimal_places=2, default=0, help_text='Maintenance/repairs to be charged to tenant', max_digits=10)),
                ('post_dated_cheques_adjusted', models.BooleanField(default=False, help_text='Whether post-dated cheques have been adjusted/cancelled')),
                ('post_dated_cheques_notes', models.TextField(blank=True, help_text='Details of cheque adjustments')),
                ('net_refund', models.DecimalField(decimal_places=2, default=0, help_text='Final amount to be refunded (or charged if negative)', max_digits=10)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('exit_notes', models.TextField(blank=True, help_text='Tenant exit notes, damage report, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='property.lease')),
            ],
            options={
                'verbose_name': 'Lease Termination',
                'verbose_name_plural': 'Lease Terminations',
                'ordering': ['-termination_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_number', models.CharField(max_length=50, unique=True)),
                ('original_start_date', models.DateField()),
                ('original_end_date', models.DateField()),
                ('original_monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_start_date', models.DateField()),
                ('new_end_date', models.DateField()),
                ('new_monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_security_deposit', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if unchanged', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('renewal_date', models.DateField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='property.lease')),
            ],
            options={
                'verbose_name': 'Lease Renewal',
                'verbose_name_plural': 'Lease Renewals',
                'ordering': ['-renewal_date'],
            },
        ),
    ]
