# Generated by Django 4.2.7 on 2026-02-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_leasetermination_leaserenewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaserenewal',
            name='renewal_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leasetermination',
            name='termination_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
