# Generated by Django 4.2.7 on 2026-02-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0007_add_lease_accounting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_ledger_account',
            field=models.BooleanField(default=True, help_text='Whether this tenant has a customer/supplier ledger account'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ledger_account',
            field=models.ForeignKey(blank=True, help_text='Customer/Supplier account in chart of accounts', limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_ledgers', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ledger_account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', help_text='Type of ledger account', max_length=20),
        ),
        migrations.AlterField(
            model_name='lease',
            name='other_charges_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'income'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_other_charges', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='refundable_deposit_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'liability'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_deposits', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='unearned_revenue_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'liability'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_unearned_revenue', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='leasetermination',
            name='deposit_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'liability'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_termination_deposits', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='leasetermination',
            name='maintenance_charges_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_termination_maintenance', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='leasetermination',
            name='penalty_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'income'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_termination_penalties', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='leasetermination',
            name='post_dated_cheques_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_termination_cheques', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='leasetermination',
            name='tenant_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_termination_tenant', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='leasetermination',
            name='unearned_revenue_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'income'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_termination_unearned', to='accounts.account'),
        ),
    ]
