# Generated by Django 4.2.7 on 2026-02-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0008_tenant_has_ledger_account_tenant_ledger_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Cost center for tenant-related tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='accounts.costcenter'),
        ),
    ]
