# Generated by Django 4.2.7 on 2026-02-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('property', '0009_tenant_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalLegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('eviction', 'Eviction'), ('non_payment', 'Non-Payment'), ('damage', 'Property Damage'), ('other', 'Other')], max_length=20)),
                ('case_number', models.CharField(help_text='External case reference number', max_length=100)),
                ('filing_date', models.DateField()),
                ('current_status', models.CharField(choices=[('filed', 'Filed'), ('in_progress', 'In Progress'), ('judgment_passed', 'Judgment Passed'), ('closed_tenant_won', 'Closed (Tenant Won)'), ('closed_owner_won', 'Closed (Owner Won)')], default='filed', max_length=30)),
                ('court_name', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_cases', to='accounts.costcenter')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_cases', to='property.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_cases', to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_cases', to='property.tenant')),
            ],
            options={
                'verbose_name': 'Rental Legal Case',
                'verbose_name_plural': 'Rental Legal Cases',
                'ordering': ['-filing_date'],
            },
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('under_legal_case', 'Under Legal Case'), ('blocked', 'Blocked')], default='vacant', max_length=25),
        ),
        migrations.CreateModel(
            name='RentalLegalCaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.CharField(max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='property.rentallegalcase')),
            ],
            options={
                'verbose_name': 'Legal Case Status History',
                'verbose_name_plural': 'Legal Case Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='rentallegalcase',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_cases', to='property.unit'),
        ),
    ]
