# Generated by Django 4.2.7 on 2026-02-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_system_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('prepaid', 'Prepaid Recognition'), ('amortization', 'Amortization'), ('receipt', 'Receipt Voucher'), ('invoice', 'Invoice Posting'), ('payment', 'Payment Voucher'), ('revenue_recognition', 'Revenue Recognition'), ('cheque', 'Cheque Movement'), ('manual', 'Manual Journal Entry')], max_length=30),
        ),
    ]
