# Generated by Django 4.2.7 on 2026-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptvoucher',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
