# Generated by Django 4.2.7 on 2026-02-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_tenant_has_ledger_account_tenant_ledger_account_and_more'),
        ('accounts', '0001_initial'),
        ('sales', '0003_add_receipt_voucher_accounting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucher',
            name='lease',
            field=models.ForeignKey(blank=True, help_text='Associated lease for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_vouchers', to='property.lease'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_bank', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='cash_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_cash', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='post_dated_cheques_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_post_dated', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='tenant_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_tenant', to='accounts.account'),
        ),
    ]
